export const ACTION_TYPES = {
  SET_ABOUT_ME_DETAILS: "SET_ABOUT_ME_DETAILS",
  SET_SKILL_SETS_DATA: "SET_SKILL_SETS_DATA",
  SET_PROJECTS: "SET_PROJECTS",
  SET_EXPERIENCE: "SET_EXPERIENCE",
  SET_CTA: "SET_CTA",
};
